#!/usr/bin/env bash
# Author: Aaron Kuehler
# Purpose: Configures the shell 

# Add pretty colors
export CLICOLOR=1

# Setup Ruby Version Manager
RVM_CONFIG=$DOFILES_THIRD_PARTY_HOME/rvm
if [ -f $RVM_CONFIG ];
   then source $RVM_CONFIG
fi

# Setup Git
GIT_CONFIG=$DOFILES_THIRD_PARTY_HOME/git
if [ -f $GIT_CONFIG ];
   then source $GIT_CONFIG
fi

# Add useful git information to propmt
function parse_git_dirty {
  [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo -e '\033[31m ☣ \033[0m'|| echo -e '\033[32m ✔ \033[0m'
}
function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/[\1$(parse_git_dirty)]/"
}
export PS1='\u@\h \[\033[1;33m\]\w\[\033[0m\]$(parse_git_branch)$ '
