#! /usr/bin/env ruby
#
# Purpose: Mirrors one heroku BNTP instance to another. Copies data
# and assets.
#
def redify(string)
  "\033[0;31m#{string}\033[0m"
end

def orangify(string)
  "\033[0;33m#{string}\033[0m"
end

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

require 'optparse'

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: copy_bntp --from instance-name --to instance-name"

  opts.on("--from [instance-name]", "Instance from which data will be copied") do |from|
    options[:from] = from
  end

  opts.on("--to [instance-name]", "Instance to which data will be copied") do |to|
    options[:to] = to
  end
end.parse!

puts "Are you sure you want to:"
puts "1.) " + redify("Destroy the database on #{options[:to]}")
puts "2.) " + orangify("Copy data the database from #{options[:from]} to #{options[:to]}")
puts "3.) " + orangify("Sync images from #{options[:from]} to #{options[:to]}")
puts "(Yes/no)?"
proceed = gets.chomp

if "Yes" == proceed
  puts "Copying database from #{options[:from]} to #{options[:to]} ..."
  system! "heroku pg:copy bntp-#{options[:from]}::DATABASE_URL DATABASE_URL --app bntp-#{options[:to]}"

  puts "Copying images from #{options[:from]} to #{options[:to]} ..."
  system! "aws s3 sync --acl public-read s3://bxm-bntp-#{options[:from]} s3://bxm-bntp-#{options[:to]}"
else
  puts "Aborting at user's request. Responded #{proceed}... "
end
