#! /usr/bin/env ruby

current_branch = `git branch | grep '*'`.strip
#unless `git branch --contains master | grep '\\#{current_branch}'`.strip == current_branch
#  puts "cannot lint check between master and head if there is no master in commit chain"
#  return
#end

diff = `git show master..head | grep -E '^\\+\\+\\+ |^@@ '`

line_ranges = {}
current_file = ''
diff.split("\n").each do |line|
  if line =~ /^\+\+\+ /
    current_file = line.split('/',2).last
    line_ranges[current_file] = []
  end

  if line =~ /^@@ /
    line_number, offset = line.scan(/\+(\d+),?(\d+)?/).flatten.map(&:to_i)
    line_ranges[current_file] << (line_number..(line_number+offset))
  end
end

error_count = 0
line_ranges.each do |file_name, ranges|
  next unless File.exist? file_name
  report = `ruby -W0 -S rubocop #{file_name} --config config/lint/.ruby-style.yml`
  report.split("\n").each do |line|
    if line_number = line.scan(/^[^:]+(\.rb|\.js):(\d+):\d+:/).flatten.map(&:to_i).last
      ranges.each do |range|
        if range.include? line_number
          puts line
          error_count += 1
        end
      end
    end
  end
end

puts "No lint errors were found!" if error_count == 0
